// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rusk.proto

package phoenix

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Provisioner struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provisioner) Reset()         { *m = Provisioner{} }
func (m *Provisioner) String() string { return proto.CompactTextString(m) }
func (*Provisioner) ProtoMessage()    {}
func (*Provisioner) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{0}
}

func (m *Provisioner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provisioner.Unmarshal(m, b)
}
func (m *Provisioner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provisioner.Marshal(b, m, deterministic)
}
func (m *Provisioner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provisioner.Merge(m, src)
}
func (m *Provisioner) XXX_Size() int {
	return xxx_messageInfo_Provisioner.Size(m)
}
func (m *Provisioner) XXX_DiscardUnknown() {
	xxx_messageInfo_Provisioner.DiscardUnknown(m)
}

var xxx_messageInfo_Provisioner proto.InternalMessageInfo

func (m *Provisioner) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type EchoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{1}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

type EchoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{2}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

type ValidateStateTransitionRequest struct {
	// List of transactions to be validated
	Txs                  []*Transaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ValidateStateTransitionRequest) Reset()         { *m = ValidateStateTransitionRequest{} }
func (m *ValidateStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionRequest) ProtoMessage()    {}
func (*ValidateStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{3}
}

func (m *ValidateStateTransitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionRequest.Unmarshal(m, b)
}
func (m *ValidateStateTransitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionRequest.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionRequest.Merge(m, src)
}
func (m *ValidateStateTransitionRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionRequest.Size(m)
}
func (m *ValidateStateTransitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionRequest proto.InternalMessageInfo

func (m *ValidateStateTransitionRequest) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ValidateStateTransitionResponse struct {
	// Status of the state transition
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateStateTransitionResponse) Reset()         { *m = ValidateStateTransitionResponse{} }
func (m *ValidateStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateStateTransitionResponse) ProtoMessage()    {}
func (*ValidateStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{4}
}

func (m *ValidateStateTransitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateStateTransitionResponse.Unmarshal(m, b)
}
func (m *ValidateStateTransitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateStateTransitionResponse.Marshal(b, m, deterministic)
}
func (m *ValidateStateTransitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateStateTransitionResponse.Merge(m, src)
}
func (m *ValidateStateTransitionResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateStateTransitionResponse.Size(m)
}
func (m *ValidateStateTransitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateStateTransitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateStateTransitionResponse proto.InternalMessageInfo

func (m *ValidateStateTransitionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DistributeRequest struct {
	TotalReward          uint64         `protobuf:"fixed64,1,opt,name=total_reward,json=totalReward,proto3" json:"total_reward,omitempty"`
	Addresses            []*Provisioner `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Pk                   *PublicKey     `protobuf:"bytes,3,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DistributeRequest) Reset()         { *m = DistributeRequest{} }
func (m *DistributeRequest) String() string { return proto.CompactTextString(m) }
func (*DistributeRequest) ProtoMessage()    {}
func (*DistributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{5}
}

func (m *DistributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeRequest.Unmarshal(m, b)
}
func (m *DistributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeRequest.Marshal(b, m, deterministic)
}
func (m *DistributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeRequest.Merge(m, src)
}
func (m *DistributeRequest) XXX_Size() int {
	return xxx_messageInfo_DistributeRequest.Size(m)
}
func (m *DistributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeRequest proto.InternalMessageInfo

func (m *DistributeRequest) GetTotalReward() uint64 {
	if m != nil {
		return m.TotalReward
	}
	return 0
}

func (m *DistributeRequest) GetAddresses() []*Provisioner {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *DistributeRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

type DistributeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeResponse) Reset()         { *m = DistributeResponse{} }
func (m *DistributeResponse) String() string { return proto.CompactTextString(m) }
func (*DistributeResponse) ProtoMessage()    {}
func (*DistributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{6}
}

func (m *DistributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeResponse.Unmarshal(m, b)
}
func (m *DistributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeResponse.Marshal(b, m, deterministic)
}
func (m *DistributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeResponse.Merge(m, src)
}
func (m *DistributeResponse) XXX_Size() int {
	return xxx_messageInfo_DistributeResponse.Size(m)
}
func (m *DistributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeResponse proto.InternalMessageInfo

func (m *DistributeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type WithdrawRequest struct {
	Signature            []byte     `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Address              []byte     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Value                uint64     `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Pk                   *PublicKey `protobuf:"bytes,4,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{7}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *WithdrawRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *WithdrawRequest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *WithdrawRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

type WithdrawResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{8}
}

func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(m, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

func (m *WithdrawResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type StakeRequest struct {
	Nullifiers           []*Nullifier         `protobuf:"bytes,1,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	Outputs              []*TransactionOutput `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Pk                   *PublicKey           `protobuf:"bytes,3,opt,name=pk,proto3" json:"pk,omitempty"`
	PkBls                []byte               `protobuf:"bytes,4,opt,name=pk_bls,json=pkBls,proto3" json:"pk_bls,omitempty"`
	Expiration           uint64               `protobuf:"fixed64,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Value                uint64               `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	CurrentHeight        uint64               `protobuf:"fixed64,7,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StakeRequest) Reset()         { *m = StakeRequest{} }
func (m *StakeRequest) String() string { return proto.CompactTextString(m) }
func (*StakeRequest) ProtoMessage()    {}
func (*StakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{9}
}

func (m *StakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeRequest.Unmarshal(m, b)
}
func (m *StakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeRequest.Marshal(b, m, deterministic)
}
func (m *StakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeRequest.Merge(m, src)
}
func (m *StakeRequest) XXX_Size() int {
	return xxx_messageInfo_StakeRequest.Size(m)
}
func (m *StakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StakeRequest proto.InternalMessageInfo

func (m *StakeRequest) GetNullifiers() []*Nullifier {
	if m != nil {
		return m.Nullifiers
	}
	return nil
}

func (m *StakeRequest) GetOutputs() []*TransactionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *StakeRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *StakeRequest) GetPkBls() []byte {
	if m != nil {
		return m.PkBls
	}
	return nil
}

func (m *StakeRequest) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *StakeRequest) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *StakeRequest) GetCurrentHeight() uint64 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

type StakeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakeResponse) Reset()         { *m = StakeResponse{} }
func (m *StakeResponse) String() string { return proto.CompactTextString(m) }
func (*StakeResponse) ProtoMessage()    {}
func (*StakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{10}
}

func (m *StakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeResponse.Unmarshal(m, b)
}
func (m *StakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeResponse.Marshal(b, m, deterministic)
}
func (m *StakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeResponse.Merge(m, src)
}
func (m *StakeResponse) XXX_Size() int {
	return xxx_messageInfo_StakeResponse.Size(m)
}
func (m *StakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StakeResponse proto.InternalMessageInfo

func (m *StakeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type WithdrawStakeRequest struct {
	Pk                   *PublicKey `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	CurrentHeight        uint64     `protobuf:"fixed64,2,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WithdrawStakeRequest) Reset()         { *m = WithdrawStakeRequest{} }
func (m *WithdrawStakeRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawStakeRequest) ProtoMessage()    {}
func (*WithdrawStakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{11}
}

func (m *WithdrawStakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawStakeRequest.Unmarshal(m, b)
}
func (m *WithdrawStakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawStakeRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawStakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawStakeRequest.Merge(m, src)
}
func (m *WithdrawStakeRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawStakeRequest.Size(m)
}
func (m *WithdrawStakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawStakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawStakeRequest proto.InternalMessageInfo

func (m *WithdrawStakeRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *WithdrawStakeRequest) GetCurrentHeight() uint64 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

type WithdrawStakeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawStakeResponse) Reset()         { *m = WithdrawStakeResponse{} }
func (m *WithdrawStakeResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawStakeResponse) ProtoMessage()    {}
func (*WithdrawStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{12}
}

func (m *WithdrawStakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawStakeResponse.Unmarshal(m, b)
}
func (m *WithdrawStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawStakeResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawStakeResponse.Merge(m, src)
}
func (m *WithdrawStakeResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawStakeResponse.Size(m)
}
func (m *WithdrawStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawStakeResponse proto.InternalMessageInfo

func (m *WithdrawStakeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SlashRequest struct {
	Pk                   *PublicKey `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	Height               uint64     `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Step                 uint64     `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Signature1           []byte     `protobuf:"bytes,4,opt,name=signature1,proto3" json:"signature1,omitempty"`
	Signature2           []byte     `protobuf:"bytes,5,opt,name=signature2,proto3" json:"signature2,omitempty"`
	Message1             []byte     `protobuf:"bytes,6,opt,name=message1,proto3" json:"message1,omitempty"`
	Message2             []byte     `protobuf:"bytes,7,opt,name=message2,proto3" json:"message2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SlashRequest) Reset()         { *m = SlashRequest{} }
func (m *SlashRequest) String() string { return proto.CompactTextString(m) }
func (*SlashRequest) ProtoMessage()    {}
func (*SlashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{13}
}

func (m *SlashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlashRequest.Unmarshal(m, b)
}
func (m *SlashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlashRequest.Marshal(b, m, deterministic)
}
func (m *SlashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashRequest.Merge(m, src)
}
func (m *SlashRequest) XXX_Size() int {
	return xxx_messageInfo_SlashRequest.Size(m)
}
func (m *SlashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SlashRequest proto.InternalMessageInfo

func (m *SlashRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *SlashRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SlashRequest) GetStep() uint64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *SlashRequest) GetSignature1() []byte {
	if m != nil {
		return m.Signature1
	}
	return nil
}

func (m *SlashRequest) GetSignature2() []byte {
	if m != nil {
		return m.Signature2
	}
	return nil
}

func (m *SlashRequest) GetMessage1() []byte {
	if m != nil {
		return m.Message1
	}
	return nil
}

func (m *SlashRequest) GetMessage2() []byte {
	if m != nil {
		return m.Message2
	}
	return nil
}

type SlashResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlashResponse) Reset()         { *m = SlashResponse{} }
func (m *SlashResponse) String() string { return proto.CompactTextString(m) }
func (*SlashResponse) ProtoMessage()    {}
func (*SlashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{14}
}

func (m *SlashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlashResponse.Unmarshal(m, b)
}
func (m *SlashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlashResponse.Marshal(b, m, deterministic)
}
func (m *SlashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashResponse.Merge(m, src)
}
func (m *SlashResponse) XXX_Size() int {
	return xxx_messageInfo_SlashResponse.Size(m)
}
func (m *SlashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlashResponse proto.InternalMessageInfo

func (m *SlashResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetStakeRequest struct {
	Pk                   *PublicKey `protobuf:"bytes,1,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetStakeRequest) Reset()         { *m = GetStakeRequest{} }
func (m *GetStakeRequest) String() string { return proto.CompactTextString(m) }
func (*GetStakeRequest) ProtoMessage()    {}
func (*GetStakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{15}
}

func (m *GetStakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStakeRequest.Unmarshal(m, b)
}
func (m *GetStakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStakeRequest.Marshal(b, m, deterministic)
}
func (m *GetStakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStakeRequest.Merge(m, src)
}
func (m *GetStakeRequest) XXX_Size() int {
	return xxx_messageInfo_GetStakeRequest.Size(m)
}
func (m *GetStakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStakeRequest proto.InternalMessageInfo

func (m *GetStakeRequest) GetPk() *PublicKey {
	if m != nil {
		return m.Pk
	}
	return nil
}

type GetStakeResponse struct {
	Value                uint64   `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	PkBls                []byte   `protobuf:"bytes,2,opt,name=pk_bls,json=pkBls,proto3" json:"pk_bls,omitempty"`
	DepositHeight        uint64   `protobuf:"fixed64,3,opt,name=deposit_height,json=depositHeight,proto3" json:"deposit_height,omitempty"`
	ExpiryHeight         uint64   `protobuf:"fixed64,4,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStakeResponse) Reset()         { *m = GetStakeResponse{} }
func (m *GetStakeResponse) String() string { return proto.CompactTextString(m) }
func (*GetStakeResponse) ProtoMessage()    {}
func (*GetStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_211ec4e18343b18f, []int{16}
}

func (m *GetStakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStakeResponse.Unmarshal(m, b)
}
func (m *GetStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStakeResponse.Marshal(b, m, deterministic)
}
func (m *GetStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStakeResponse.Merge(m, src)
}
func (m *GetStakeResponse) XXX_Size() int {
	return xxx_messageInfo_GetStakeResponse.Size(m)
}
func (m *GetStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStakeResponse proto.InternalMessageInfo

func (m *GetStakeResponse) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *GetStakeResponse) GetPkBls() []byte {
	if m != nil {
		return m.PkBls
	}
	return nil
}

func (m *GetStakeResponse) GetDepositHeight() uint64 {
	if m != nil {
		return m.DepositHeight
	}
	return 0
}

func (m *GetStakeResponse) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Provisioner)(nil), "phoenix.Provisioner")
	proto.RegisterType((*EchoRequest)(nil), "phoenix.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "phoenix.EchoResponse")
	proto.RegisterType((*ValidateStateTransitionRequest)(nil), "phoenix.ValidateStateTransitionRequest")
	proto.RegisterType((*ValidateStateTransitionResponse)(nil), "phoenix.ValidateStateTransitionResponse")
	proto.RegisterType((*DistributeRequest)(nil), "phoenix.DistributeRequest")
	proto.RegisterType((*DistributeResponse)(nil), "phoenix.DistributeResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "phoenix.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "phoenix.WithdrawResponse")
	proto.RegisterType((*StakeRequest)(nil), "phoenix.StakeRequest")
	proto.RegisterType((*StakeResponse)(nil), "phoenix.StakeResponse")
	proto.RegisterType((*WithdrawStakeRequest)(nil), "phoenix.WithdrawStakeRequest")
	proto.RegisterType((*WithdrawStakeResponse)(nil), "phoenix.WithdrawStakeResponse")
	proto.RegisterType((*SlashRequest)(nil), "phoenix.SlashRequest")
	proto.RegisterType((*SlashResponse)(nil), "phoenix.SlashResponse")
	proto.RegisterType((*GetStakeRequest)(nil), "phoenix.GetStakeRequest")
	proto.RegisterType((*GetStakeResponse)(nil), "phoenix.GetStakeResponse")
}

func init() {
	proto.RegisterFile("rusk.proto", fileDescriptor_211ec4e18343b18f)
}

var fileDescriptor_211ec4e18343b18f = []byte{
	// 762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x6d, 0x6f, 0xd3, 0x3a,
	0x14, 0x5e, 0xba, 0xbe, 0x6c, 0xa7, 0xe9, 0x5e, 0xac, 0x6d, 0xb7, 0x37, 0xf7, 0xde, 0xdd, 0x11,
	0x34, 0x56, 0x24, 0x54, 0x69, 0x81, 0x49, 0x48, 0x7c, 0x02, 0x81, 0x36, 0x09, 0x09, 0x26, 0x6f,
	0x82, 0x8f, 0x93, 0xdb, 0x9a, 0xd5, 0x4a, 0x48, 0x82, 0xed, 0xec, 0xe5, 0x33, 0x1f, 0x91, 0x10,
	0xbf, 0x89, 0x1f, 0xc1, 0xef, 0x41, 0x71, 0xe2, 0xd8, 0xed, 0xba, 0x95, 0x7d, 0x8b, 0xcf, 0x39,
	0xf6, 0x79, 0xfc, 0x3c, 0x8f, 0x8f, 0x02, 0xc0, 0x33, 0x11, 0xf6, 0x53, 0x9e, 0xc8, 0x04, 0xb5,
	0xd2, 0x71, 0x42, 0x63, 0x76, 0xe5, 0xad, 0x4b, 0x4e, 0x62, 0x41, 0x86, 0x92, 0x25, 0x71, 0x91,
	0xf3, 0x20, 0xa4, 0xd7, 0x42, 0x7f, 0xc7, 0x89, 0xa4, 0xc5, 0xb7, 0xbf, 0x07, 0xed, 0x63, 0x9e,
	0x5c, 0x30, 0xc1, 0x92, 0x98, 0x72, 0xd4, 0x85, 0x16, 0x19, 0x8d, 0x38, 0x15, 0xa2, 0xeb, 0xec,
	0x38, 0x3d, 0x17, 0xeb, 0xa5, 0xdf, 0x81, 0xf6, 0x9b, 0xe1, 0x38, 0xc1, 0xf4, 0x4b, 0x46, 0x85,
	0xf4, 0x57, 0xc0, 0x2d, 0x96, 0x22, 0x4d, 0x62, 0x41, 0xfd, 0x23, 0xd8, 0xfe, 0x40, 0x22, 0x36,
	0x22, 0x92, 0x9e, 0x48, 0x22, 0xe9, 0x69, 0x8e, 0x80, 0xe5, 0x00, 0xca, 0x1d, 0xe8, 0x11, 0x2c,
	0xca, 0xab, 0xfc, 0xd8, 0xc5, 0x5e, 0x3b, 0xd8, 0xe8, 0x97, 0x58, 0xfb, 0xa7, 0x06, 0x2a, 0xce,
	0x0b, 0xfc, 0x17, 0xf0, 0xff, 0xad, 0x27, 0x15, 0xcd, 0x72, 0x94, 0x22, 0x1b, 0x0e, 0x35, 0xca,
	0x25, 0xac, 0x97, 0xfe, 0x77, 0x07, 0xd6, 0x5f, 0x33, 0x21, 0x39, 0x1b, 0x64, 0x92, 0xea, 0xd6,
	0x0f, 0xc0, 0x95, 0x89, 0x24, 0xd1, 0x19, 0xa7, 0x97, 0x84, 0x8f, 0xd4, 0xa6, 0x26, 0x6e, 0xab,
	0x18, 0x56, 0x21, 0x14, 0xc0, 0x72, 0x79, 0x53, 0x2a, 0xba, 0xb5, 0x29, 0x8c, 0x16, 0x43, 0xd8,
	0x94, 0x21, 0x1f, 0x6a, 0x69, 0xd8, 0x5d, 0xdc, 0x71, 0x7a, 0xed, 0x00, 0x99, 0xe2, 0x6c, 0x10,
	0xb1, 0xe1, 0x5b, 0x7a, 0x8d, 0x6b, 0x69, 0xe8, 0xf7, 0x01, 0xd9, 0x78, 0xe6, 0x5e, 0xe0, 0xab,
	0x03, 0xab, 0x1f, 0x99, 0x1c, 0x8f, 0x38, 0xb9, 0xd4, 0xf0, 0xff, 0x85, 0x65, 0xc1, 0xce, 0x63,
	0x22, 0x33, 0x4e, 0x4b, 0x59, 0x4c, 0xc0, 0x96, 0xac, 0x36, 0x21, 0x19, 0xda, 0x80, 0xc6, 0x05,
	0x89, 0x32, 0xaa, 0x20, 0x36, 0x71, 0xb1, 0x28, 0x51, 0xd7, 0xef, 0x44, 0xfd, 0x04, 0xd6, 0x0c,
	0x88, 0xb9, 0x98, 0x7f, 0xd4, 0xc0, 0x3d, 0x91, 0x24, 0xac, 0xf8, 0x0e, 0x00, 0xe2, 0x2c, 0x8a,
	0xd8, 0x27, 0x46, 0xb9, 0x56, 0xdc, 0xb4, 0x7a, 0xa7, 0x53, 0xd8, 0xaa, 0x42, 0xcf, 0xa0, 0x95,
	0x64, 0x32, 0xcd, 0xa4, 0xa6, 0xdf, 0x9b, 0x65, 0x91, 0xf7, 0xaa, 0x04, 0xeb, 0xd2, 0x3f, 0x91,
	0x00, 0x6d, 0x42, 0x33, 0x0d, 0xcf, 0x06, 0x91, 0x50, 0x97, 0x76, 0x71, 0x23, 0x0d, 0x5f, 0x45,
	0x02, 0x6d, 0x03, 0xd0, 0xab, 0x94, 0x71, 0x92, 0x9f, 0xdb, 0x6d, 0x28, 0x8a, 0xac, 0x88, 0x61,
	0xaf, 0x69, 0xb3, 0xb7, 0x0b, 0x2b, 0xc3, 0x8c, 0x73, 0x1a, 0xcb, 0xb3, 0x31, 0x65, 0xe7, 0x63,
	0xd9, 0x6d, 0xa9, 0x74, 0xa7, 0x8c, 0x1e, 0xa9, 0xa0, 0xff, 0x18, 0x3a, 0x25, 0x23, 0x73, 0xd9,
	0x23, 0xb0, 0xa1, 0xb9, 0x9e, 0x20, 0xb1, 0xb8, 0x9a, 0x73, 0xe7, 0xd5, 0x6e, 0xa2, 0xa9, 0xcd,
	0x42, 0xb3, 0x0f, 0x9b, 0x53, 0x2d, 0xe6, 0xa2, 0xfa, 0xe5, 0x80, 0x7b, 0x12, 0x11, 0x31, 0xbe,
	0x0f, 0x9c, 0x2d, 0x68, 0x4e, 0xc0, 0x28, 0x57, 0x08, 0x41, 0x5d, 0x48, 0x9a, 0x2a, 0x9d, 0xea,
	0x58, 0x7d, 0xe7, 0xf4, 0x57, 0x1e, 0xde, 0x2f, 0x95, 0xb1, 0x22, 0x13, 0xf9, 0x40, 0xc9, 0x63,
	0xe7, 0x03, 0xe4, 0xc1, 0xd2, 0x67, 0x2a, 0x04, 0x39, 0xa7, 0xfb, 0x4a, 0x21, 0x17, 0x57, 0x6b,
	0x2b, 0x17, 0x28, 0x79, 0x4c, 0x2e, 0x50, 0xca, 0x14, 0xf7, 0x9a, 0xcb, 0xc1, 0x01, 0xac, 0x1e,
	0x52, 0x79, 0x5f, 0x51, 0xfc, 0x6f, 0x0e, 0xac, 0x99, 0x7d, 0x65, 0x97, 0xca, 0x4d, 0x8e, 0xed,
	0x26, 0x63, 0xcd, 0x9a, 0x6d, 0xcd, 0x5d, 0x58, 0x19, 0xd1, 0x34, 0x11, 0xac, 0x92, 0xb5, 0x78,
	0xc1, 0x9d, 0x32, 0x5a, 0xc8, 0x8a, 0x1e, 0x42, 0x47, 0xf9, 0xf5, 0x5a, 0x57, 0xd5, 0x55, 0x95,
	0x5b, 0x04, 0x8b, 0xa2, 0xe0, 0x67, 0x1d, 0xea, 0x38, 0x13, 0x21, 0x3a, 0x80, 0x7a, 0x3e, 0xb1,
	0x91, 0x19, 0x6b, 0xd6, 0x3c, 0xf7, 0x36, 0xa7, 0xa2, 0xe5, 0x58, 0x5f, 0x40, 0x31, 0xfc, 0x75,
	0xcb, 0x38, 0x46, 0x7b, 0xd5, 0x9e, 0xbb, 0x47, 0xbf, 0xd7, 0x9b, 0x5f, 0x58, 0xf5, 0x3b, 0x04,
	0x30, 0x03, 0x13, 0x99, 0x21, 0x70, 0x63, 0xaa, 0x7b, 0xff, 0xcc, 0xcc, 0x55, 0x07, 0xbd, 0x84,
	0x25, 0x6d, 0x7a, 0xd4, 0xad, 0x4a, 0xa7, 0x66, 0xab, 0xf7, 0xf7, 0x8c, 0x4c, 0x75, 0xc4, 0x73,
	0x68, 0x28, 0x15, 0x91, 0x61, 0xc7, 0x76, 0x83, 0xb7, 0x35, 0x1d, 0xae, 0x76, 0x1e, 0x43, 0x67,
	0xe2, 0xc5, 0xa1, 0xff, 0x6e, 0xf4, 0x99, 0x38, 0x69, 0xfb, 0xb6, 0xf4, 0x04, 0x96, 0xdc, 0xb7,
	0x36, 0x16, 0xeb, 0x7d, 0xda, 0x58, 0x6c, 0x7b, 0x17, 0x44, 0x68, 0x3b, 0x5a, 0x44, 0x4c, 0x39,
	0xdb, 0x22, 0x62, 0xda, 0xbb, 0xfe, 0xc2, 0xa0, 0xa9, 0x7e, 0x16, 0x9e, 0xfe, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x83, 0x96, 0x46, 0xdf, 0x6e, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RuskClient is the client API for Rusk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuskClient interface {
	// Simple echo request
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Validate a set of transactions, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error)
	Distribute(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*DistributeResponse, error)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
	Stake(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*StakeResponse, error)
	WithdrawStake(ctx context.Context, in *WithdrawStakeRequest, opts ...grpc.CallOption) (*WithdrawStakeResponse, error)
	Slash(ctx context.Context, in *SlashRequest, opts ...grpc.CallOption) (*SlashResponse, error)
	GetStake(ctx context.Context, in *GetStakeRequest, opts ...grpc.CallOption) (*GetStakeResponse, error)
}

type ruskClient struct {
	cc grpc.ClientConnInterface
}

func NewRuskClient(cc grpc.ClientConnInterface) RuskClient {
	return &ruskClient{cc}
}

func (c *ruskClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) ValidateStateTransition(ctx context.Context, in *ValidateStateTransitionRequest, opts ...grpc.CallOption) (*ValidateStateTransitionResponse, error) {
	out := new(ValidateStateTransitionResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/ValidateStateTransition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Distribute(ctx context.Context, in *DistributeRequest, opts ...grpc.CallOption) (*DistributeResponse, error) {
	out := new(DistributeResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Distribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Stake(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*StakeResponse, error) {
	out := new(StakeResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Stake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) WithdrawStake(ctx context.Context, in *WithdrawStakeRequest, opts ...grpc.CallOption) (*WithdrawStakeResponse, error) {
	out := new(WithdrawStakeResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/WithdrawStake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) Slash(ctx context.Context, in *SlashRequest, opts ...grpc.CallOption) (*SlashResponse, error) {
	out := new(SlashResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/Slash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruskClient) GetStake(ctx context.Context, in *GetStakeRequest, opts ...grpc.CallOption) (*GetStakeResponse, error) {
	out := new(GetStakeResponse)
	err := c.cc.Invoke(ctx, "/phoenix.Rusk/GetStake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuskServer is the server API for Rusk service.
type RuskServer interface {
	// Simple echo request
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Validate a set of transactions, returning false if at least one of the
	// listed transactions is inconsistent
	ValidateStateTransition(context.Context, *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error)
	Distribute(context.Context, *DistributeRequest) (*DistributeResponse, error)
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
	Stake(context.Context, *StakeRequest) (*StakeResponse, error)
	WithdrawStake(context.Context, *WithdrawStakeRequest) (*WithdrawStakeResponse, error)
	Slash(context.Context, *SlashRequest) (*SlashResponse, error)
	GetStake(context.Context, *GetStakeRequest) (*GetStakeResponse, error)
}

// UnimplementedRuskServer can be embedded to have forward compatible implementations.
type UnimplementedRuskServer struct {
}

func (*UnimplementedRuskServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedRuskServer) ValidateStateTransition(ctx context.Context, req *ValidateStateTransitionRequest) (*ValidateStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStateTransition not implemented")
}
func (*UnimplementedRuskServer) Distribute(ctx context.Context, req *DistributeRequest) (*DistributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distribute not implemented")
}
func (*UnimplementedRuskServer) Withdraw(ctx context.Context, req *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedRuskServer) Stake(ctx context.Context, req *StakeRequest) (*StakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stake not implemented")
}
func (*UnimplementedRuskServer) WithdrawStake(ctx context.Context, req *WithdrawStakeRequest) (*WithdrawStakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawStake not implemented")
}
func (*UnimplementedRuskServer) Slash(ctx context.Context, req *SlashRequest) (*SlashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Slash not implemented")
}
func (*UnimplementedRuskServer) GetStake(ctx context.Context, req *GetStakeRequest) (*GetStakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStake not implemented")
}

func RegisterRuskServer(s *grpc.Server, srv RuskServer) {
	s.RegisterService(&_Rusk_serviceDesc, srv)
}

func _Rusk_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_ValidateStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).ValidateStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/ValidateStateTransition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).ValidateStateTransition(ctx, req.(*ValidateStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Distribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Distribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Distribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Distribute(ctx, req.(*DistributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Stake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Stake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Stake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Stake(ctx, req.(*StakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_WithdrawStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawStakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).WithdrawStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/WithdrawStake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).WithdrawStake(ctx, req.(*WithdrawStakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_Slash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).Slash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/Slash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).Slash(ctx, req.(*SlashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rusk_GetStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuskServer).GetStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.Rusk/GetStake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuskServer).GetStake(ctx, req.(*GetStakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rusk_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phoenix.Rusk",
	HandlerType: (*RuskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Rusk_Echo_Handler,
		},
		{
			MethodName: "ValidateStateTransition",
			Handler:    _Rusk_ValidateStateTransition_Handler,
		},
		{
			MethodName: "Distribute",
			Handler:    _Rusk_Distribute_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _Rusk_Withdraw_Handler,
		},
		{
			MethodName: "Stake",
			Handler:    _Rusk_Stake_Handler,
		},
		{
			MethodName: "WithdrawStake",
			Handler:    _Rusk_WithdrawStake_Handler,
		},
		{
			MethodName: "Slash",
			Handler:    _Rusk_Slash_Handler,
		},
		{
			MethodName: "GetStake",
			Handler:    _Rusk_GetStake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rusk.proto",
}
